### ISSUE TITLE
Update AlgoSDK: Failed to execute on Window: illegal invocation 

### ISSUE THREAD

**Issue by Michele971** [algorandfoundation/algokit-utils-ts#158]
This is the same error cited here: https://github.com/algorand/js-algorand-sdk/issues/823 .

I have inspected algokit dependencies and I saw that you are still using algosdk 2.5.0.

You have to update your library, otherwise we can not set out algoClient using algokit utils. The new algosdk version is 2.7.0.

**Comment by robdmoore** [comment]
We have algosdk as a [peer dependency](https://github.com/algorandfoundation/algokit-utils-ts/blob/main/package.json#L83) so you can independantly update it in your project, but thanks for reporting - we'll make sure to bump the minimum version next release.

**Comment by neilcampbell** [comment]
FYI the peer dependency version has been bumped in `5.0.0`
