### ISSUE TITLE
Algonode Retry Fails 429 JSON Failure (Indexer)

### ISSUE THREAD

**Issue by ShoGinn** [algorandfoundation/algokit-utils-ts#164]
When "spamming" indexer calls Algonode doesnt return a error.code but an error.statusCode

```
SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
    at JSON.parse (<anonymous>)
    at HTTPClient.parseJSON (/mycode/node_modules/.pnpm/algosdk@2.7.0/node_modules/algosdk/dist/cjs/client/client.js:96:37)
    at HTTPClient.prepareResponse (/mycode/node_modules/.pnpm/algosdk@2.7.0/node_modules/algosdk/dist/cjs/client/client.js:144:31)
    at HTTPClient.prepareResponseError (/mycode/node_modules/.pnpm/algosdk@2.7.0/node_modules/algosdk/dist/cjs/client/client.js:162:39)
    at HTTPClient.get (/mycode/node_modules/.pnpm/algosdk@2.7.0/node_modules/algosdk/dist/cjs/client/client.js:187:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LookupAssetBalances.do (/mycode/node_modules/.pnpm/algosdk@2.7.0/node_modules/algosdk/dist/cjs/client/v2/jsonrequest.js:49:21)
    at async Algorand.lookupAssetBalances (file:///mycode/build/esm/services/algorand.js:131:29)
    at async file:///mycode/build/esm/services/algo-nft-assets.js:75:31
    at async Promise.all (index 465) {
  rawResponse: '<html>\r\n' +
    '<head><title>429 Too Many Requests</title></head>\r\n' +
    '<body>\r\n' +
    '<center><h1>429 Too Many Requests</h1></center>\r\n' +
    '<hr><center>openresty</center>\r\n' +
    '</body>\r\n' +
    '</html>\r\n',
  statusCode: 429
}
```

This was an attempt on the indexer using a generic instantiation:

```
  private algodClient = algokit.getAlgoClient(algokit.getAlgoNodeConfig('mainnet', 'algod'));
  private indexerClient = algokit.getAlgoIndexerClient(
    algokit.getAlgoNodeConfig('mainnet', 'indexer'),
  );
```

I use it to lookup ownership of nfts:

```
  async lookupAssetBalances(
    assetIndex: number,
    getAll?: boolean | undefined,
  ): Promise<MiniAssetHolding[]> {
    let holders: MiniAssetHolding[] = [];
    let nextToken: string | undefined;
    do {
      const response = this.indexerClient.lookupAssetBalances(assetIndex).includeAll(getAll);
      if (nextToken) {
        response.nextToken(nextToken);
      }
      const result = (await response.do()) as LookupAssetBalancesResponse;

      holders = [
        ...holders,
        ...(result['balances']?.filter((balance) => balance.amount > 0) || []),
      ];
      nextToken = result?.['next-token'];
    } while (nextToken !== undefined);
    return holders;
  }
```

Upstream i map a promise to push 1000+ assetIndex's and with my old wrapper:

```
import algosdk from 'algosdk';
import Bottleneck from 'bottleneck';
import { DecorateAll } from 'decorate-all';

const limiter = new Bottleneck();
limiter.on('failed', (error, jobInfo) => {
  // 429 == rate limit
  // The return is the number of milliseconds to wait before retrying
  if (error.statusCode === 429 && jobInfo.retryCount < 3) {
    return 250;
  }
  if (error.statusCode === 429 && jobInfo.retryCount >= 3) {
    return 1000;
  }
  return 0;
});
const RateLimit = function (
  _target: unknown,
  _propertyKey: string | symbol,
  descriptor?: PropertyDescriptor,
): void {
  if (!descriptor) {
    return;
  }
  const original = descriptor.value;
  descriptor.value = function () {
    // eslint-disable-next-line prefer-rest-params
    const call = Reflect.apply(original, this, arguments);
    const originalDo = call.do;
    call.do = limiter.wrap(originalDo);
    return call;
  };
};

@DecorateAll(RateLimit, { deep: true })
export class WrappedIndexer extends algosdk.Indexer {}
```

my wrapper is not as clean as an HTTP inject but hope this helps diagnose

**Comment by robdmoore** [comment]
We have [retry logic in there for algod client](https://github.com/algorandfoundation/algokit-utils-ts/blob/main/src/network-client.ts#L131), but not for indexer client. This is something that could be added though, we're happy to accept a pull request or @Loedn can prioritise against other enhancements.

In this case you might want to chunk the calls to groups of 30 or so at a time to reduce the likelihood of getting rate limited.

**Comment by ShoGinn** [comment]
@robdmoore unless I'm looking at the code wrong, the indexer client is instanced the same way as the algod client with the retry client.

**Comment by robdmoore** [comment]
Oh cool, yeah, right you are!

Plus 429 is included in the retry: https://github.com/algorandfoundation/algokit-utils-ts/blob/54521df5f70ac4132ff322556ab11f74de11fc09/src/types/algo-http-client-with-retry.ts#L12

Are you finding that it's not retrying or that there are too many requests being issued so even with retries it's still failing?

**Comment by ShoGinn** [comment]
So I'm debugging the http-client now and i'm getting these errors with my spam command after I modified the code, I had to add these lines to even get it to retry rather than just throwing an error --
*this is a hack code for now*
```ts        // Only retry for one of the hardcoded conditions
        let errStatus = err.status
        if (!errStatus && typeof err.message === 'string') {
          const match = err.message.match(/Received status (\d+)/)
          if (match) {
            errStatus = parseInt(match[1], 10)
          }
        }

        if (
          !(
            AlgoHttpClientWithRetry.RETRY_ERROR_CODES.includes(err.code) ||
            AlgoHttpClientWithRetry.RETRY_STATUS_CODES.includes(err.status) ||
            AlgoHttpClientWithRetry.RETRY_STATUS_CODES.includes(errStatus)
          )
        ) {
          throw err
        }

```

`algosdk request failed 2 times. Retrying in 2000ms: URLTokenBaseHTTPError: Network request error. Received status 429 (Too Many Requests)`

And when you look at the non-modified code:
https://github.com/algorandfoundation/algokit-utils-ts/blob/54521df5f70ac4132ff322556ab11f74de11fc09/src/types/algo-http-client-with-retry.ts#L36-L41

Because it only looking for the `error.code` and `error.status` for the message and because this is in URLTokenBaseHTTPError 

That code processes the errors if it's not `res.ok` and converts it to this format of error:

https://github.com/algorand/js-algorand-sdk/blob/7965d1c194186e5c7b8a86756c546f2ec35291cd/src/client/urlTokenBaseHTTPClient.ts#L109-L139

I am curious if this is just unique to the indexer on algonode?

**Comment by ShoGinn** [comment]
@robdmoore so would you consider this a fix or an enhancement ?

I'd angle my view that this is a fix.

**Comment by robdmoore** [comment]
Mind giving this a crack: https://github.com/algorandfoundation/algokit-utils-ts/pull/165

**Comment by ShoGinn** [comment]
@robdmoore provided some feedback and changes; I am also looping in @neilcampbell since he's also helping on this!

Thanks for taking the bull by the horns on this one and getting it setup!

**Comment by robdmoore** [comment]
Let me know if this is resolved now so I can close the issue :)

**Comment by ShoGinn** [comment]
Concur! Good Fix!
