### ISSUE TITLE
Further investigate imports from algokit utils on cjs failing to resolve module when running eslint 

### ISSUE THREAD

**Issue by aorumbayev** [algorandfoundation/algokit-utils-ts#175]
Reported by @joe-p , imports of AppClient from utils types path fails during eslint module resolution on https://github.com/algorandfoundation/TEALScript/pull/244/commits/1fe51cdb2e7059afb606c5215584a395c6b2c950. 

Current fix suggested is to apply -> https://www.npmjs.com/package/eslint-config-airbnb-typescript given that airbnb plugin seems to have certain issues when it comes to module resolution and typescript.

**Comment by neilcampbell** [comment]
We are currently converting the project to bundle using Rollup (via #188), and we've tested a configuration which allows us to fix this issue.

**Comment by neilcampbell** [comment]
@joe-p We have updated the bundle to fix this issue you were having. Please update to `5.4.0`
