### ISSUE TITLE
Add ability to supress logs on smart contract clients at the client level

### ISSUE THREAD

**Issue by aorumbayev** [algorandfoundation/algokit-utils-ts#196]
In the TS client at least (but possibly the PY client too), logging of transactions is on by default but can be suppressed on a particular call by providing { sendParams: { suppressLogs: true }}. This is not a viable solution if you wish to ensure logs are suppressed on every call. A better solution would be to add a configuration option to the client itself which is used as a default.

**Comment by neilcampbell** [comment]
This can be done by registering a `nullLogger`.

```
Config.configure({ logger: nullLogger })
```
