### ISSUE TITLE
Support modified LogicError message in algod 3.22

### ISSUE THREAD

**Issue by daniel-makerx** [algorandfoundation/algokit-utils-ts#223]
### Subject of the issue

Version 3.22 of algod modified the error message when a LogicError occurs in a transaction, this change means the regex used to identify LogicErrors and extract the program count no longer works

### Steps to reproduce

1. Run `algokit localnet reset --update` This will get the latest algod image
2. Run tests

### Expected behaviour

Tests pass

### Actual behaviour

Tests fail

**Comment by neilcampbell** [comment]
Looking to get this fixed today
