### ISSUE TITLE
Enhance the dev experience for generating debug assets from a web browser

### ISSUE THREAD

**Issue by neilcampbell** [algorandfoundation/algokit-utils-ts#235]
## Problem

The mechanisms for auto generating the assets used for launching a debug session, intentionally don't work in a web browser, as we don't have access to the file system.

Some users don't run a backend in their project and all smart contract interactions are via the web browser. In these scenarios we don't offer a slick way to generate the debug assets easily.

Naturally we still have the constraint of not being able to write to the file system, however it would be good to have an easy to understand process for generating these assets when consuming a generated typed client from within a web browser, even if the process requires some additional manual steps.

See there here for context:
https://discord.com/channels/491256308461207573/1065320801970180168/1216511775995072742

**Comment by SilentRhetoric** [comment]
Will be very helpful to support people building client-side apps!

**Comment by neilcampbell** [comment]
Docs for this are here: https://github.com/algorandfoundation/algokit-utils-ts/blob/main/docs/capabilities/debugging.md#debugging-in-browser-environment
