### ISSUE TITLE
Populate Resources of a method call and return transactions array

### ISSUE THREAD

**Issue by webdevalgo** [algorandfoundation/algokit-utils-ts#271]
## Problem

Currently calling a method on client generate just sends transactions to the blockchain but there can be cases where it would be very useful to call two or many methods on that client in same txn group.

For example:
Trying to call `client.approve()` and `client.sell()`, has to be in two different txn groups.

## Solution

We can add an option to method calls so it returns array of txns instead of sending it to the blockchain.

```ts
const approveTxns = await client.approve(...args,{ returnTxns: true });
const sellTxns = await client.sell(...sellArgs,{ returnTxns: true });
const allTxns = [...aproveTxns, ...sellTxns];
for(const txn of allTxns){
    txn.group = undefined;
}
algosdk.assignGroup(allTxns);
algod.sendTransactions(allTxns);
```

**Comment by robdmoore** [comment]
You can also use `.compose` to compose multiple calls together into one atomic group :)

**Comment by webdevalgo** [comment]
Getting this error with `populateAppCallResources()`

```txt
Box ref with appId xxxxxx not in foreign-apps
```
