### ISSUE TITLE
publicKey is undefined for Address generated by `AlgorandClient.account.random()`

### ISSUE THREAD

**Issue by joe-p** [algorandfoundation/algokit-utils-ts#348]
### Subject of the issue

`account.random()` is generating accounts fine, but the Address has an undefined publicKey which is unexpected since it should always be determined upon construction.

### Your environment

8.0.1

### Steps to reproduce

1. `algorand.account.random().addr.publicKey`

### Expected behaviour

`UInt8Array` of the public key for the address

### Actual behaviour

`undefined`

**Comment by neilcampbell** [comment]
Thanks for reporting. It looks like the type needs tweaking. We'll get that fixed.
